

global COLOR_NAMES = Dictionary \
	#( 	#ORANGE,	color 225 60 0	) \
	#( 	#MAGENTA,	color 225 0 255	) \
	#( 	#BLUE, 	color 0 135 255	) \
	#( 	#PINK, 	color 190 100 120	) \
	#( 	#CYAN, 	color 0 255 255	) \
	#( 	#RED, 	color 255 0 0	) \
	#( 	#GREEN, 	color 0 255 0	) \
	#( 	#WHITE, 	color 255 255 255	) \
	#( 	#BLACK, 	color 0 0 0	) \
	#( 	#YELLOW, 	color 255 255 0	) \
	#( 	#BROWN, 	color 139 69 19	) \
	#( 	#GRAY, 	color 128 128 128	) 
	
